name: Bug report
title: "[Bug] "
labels: bug
body:
  - type: textarea
    id: describe
    attributes: 
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes: 
      label: What are the steps to reproduce
      description: If you are unsure of how to reproduce, the give us as much info about what you where doing when the bug happened
      placeholder: >
        Steps to reproduce the behavior:
        1.
        2.
        3.
        4.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes: 
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: error
    attributes: 
      label: Error id
      description: The error id you got (if applicable)
    validations:
      required: false
